### ISSUE TITLE
Get used to unit testing tensorflow and nn's

### ISSUE THREAD

**Issue by Paeti** [Paeti/IPNeuronaleNetze#31]
## Unit testing tensorflow
inform you about how to test unit tensorflow, which libraries you need etc.
write a little test example(like for a test nn you programmed)

**Comment by ChrisKre** [comment]
**Needed librarys:**        

-  Unittest : Make use of "unittest.TestCase"Class

            

-  Consider to use mltest library: 
Benefits: 
 Test suite for machine learning in tensorflow with 
  Allready implemented test functions for tensors
  Easy and quick to use

**Recommendations for test patterns:**

- Keep them deterministic        

- Keep the tests short         

**Example structure for a unit test:**  
`class Test(unittest.TestCase):`
&nbsp;&nbsp;&nbsp;``     def test_1(self):``
&nbsp;&nbsp;&nbsp;````   self.assertEqual(True, True)````

**Example unit test for a given accuracy function:**
`class accuracy_test(tf.test.TestCase):`
&nbsp;&nbsp;&nbsp;``    def accuracy_exact_test(self):``
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;```    with self.test_session():```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;````	    test_preds 0 [[0.9, 0.1], [0.01 , 0.99]] ````
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;````	    test_targets = [0, 1]````
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;````	    test_acc = get_accuracy(test_preds, test_targets)````
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;````	    self.assertEqual(test_acc.eval(), 100)````

**Sources:**
unit testing
https://guillaumegenthial.github.io/testing.html

mltest
https://github.com/Thenerdstation/mltest/blob/master/README.md 
https://medium.com/@keeper6928/mltest-automatically-test-neural-network-models-in-one-function-call-eb6f1fa5019d

**Note:** 
Test nn not yet implemented at this point.
Example test may be added afterwards.
