### ISSUE TITLE
Check if VGG-16 is a good choice

### ISSUE THREAD

**Issue by Paeti** [Paeti/IPNeuronaleNetze#8]
I found that VGG-16 convolutional networks are good for age and gender estimation.
This needs to be checked.
research:
- which group of neural networks is best for our task
- which specific network would you choose
- are convolutional nn and VGG-16 a good choice

Link convolutional nn:
[konvolutionsnetze](https://www.oreilly.de/common/leseproben//13168/2_Konvolutionsnetze.pdf)
Link paper about VGG-16 for age estimation:
[dex deep expection of apparent age from a single image](https://www.researchgate.net/publication/283356929_DEX_Deep_EXpectation_of_Apparent_Age_from_a_Single_Image)
Link tutorial implementing VGG-16:
[learning keras by implementing vgg from scratch](https://hackernoon.com/learning-keras-by-implementing-vgg16-from-scratch-d036733f2d5)

summarize the results and add them to our docs.
(Please use markdown)

**Comment by mooxl** [comment]
link to the paper about VGG-16 for age estimation is broken

**Comment by Paeti** [comment]
Thanks, link is now fixed @mooxl

**Comment by frzifus** [comment]
@DZvO I don't think it's the best idea to use the github wiki. if the repo is forked or moved, the complete documentation will be lost.

**Comment by Paeti** [comment]
moved Alex research to docs/research_results.md
